### ISSUE TITLE
About the belt model

### ISSUE THREAD

**Issue by rabbit-zc** [Nate711/StanfordDoggoProject#10]
First thank you for making the doggo open source. 
Then,My friends and I are planning to make one.
Now I want to check if the belt is this model:

![3mm - GT®2 Timing Belts](https://user-images.githubusercontent.com/50861039/58774874-3b02d080-85f6-11e9-896b-229b0540208a.JPG)
![A 6R53M070060](https://user-images.githubusercontent.com/50861039/58774883-3dfdc100-85f6-11e9-85a2-4a4db36cd461.JPG)

thank you
Looking forward to your reply

**Comment by Nate711** [comment]
That's the one! Let me know when you get to fabricating the coaxial tubes because I might have some ideas on how to make it easier on you guys.

**Comment by Nate711** [comment]
By the way if the GT2 belts are out of stock, the GT3 belts will work as well.

**Comment by rabbit-zc** [comment]
OK,thank you.
