### ISSUE TITLE
Linkage foot silicone rubber hardness?

### ISSUE THREAD

**Issue by HelloPlanet** [Nate711/StanfordDoggoProject#12]
Hi Nate and team,

As i have mentioned, I'm working on building a Doggo. (Yay! Thanks!)

While choosing silicone material for Doggo's feet,
 I noticed the silicone rubber in BOM, Dragon Skin™ 30, 
has a hardness of Shore Hardness 30A. 

As i haven't placed order yet, the options I have is from 30A to 90A. 
Do I need to choose harder or softer rubber? Please advise. Thanks!

**Comment by Nate711** [comment]
Sorry HelloPlanet for the delay! I would recommend the softer 30A rubber. Thanks!
