### ISSUE TITLE
how to use microcontroller to read encoder data from Odrive?

### ISSUE THREAD

**Issue by csyyzhang** [Nate711/StanfordDoggoProject#15]
Hi. Nice job! I have a problem with using microcontrollers to communicate with Odrive. I try to read encoder data by following the example given in the Odrive Arduino library. However, no matter what happens, whether the motor is moving or not, the return data is always 0. I have checked the connections by using the Odrive tool for PC, and it can read the encoder data properly. Do you have any suggestions for me? Thanks.

**Comment by Nate711** [comment]
Hi there, could you post your code and maybe a picture of your wiring setup? Thanks!
