### ISSUE TITLE
Some Detailed Questions about Doggo's PDB

### ISSUE THREAD

**Issue by charemax** [Nate711/StanfordDoggoProject#17]
Hi，My mentor and I are very interested in your doggo project. Can you tell me the details about Odrive's PDB?Which type of PDB is it?

**Comment by kigerzh** [comment]
It was listed in the BOM :  "Makerfire FCHUB-6s" 
![O1CN012FY7sOaOmwruxbL_!!2792988891](https://user-images.githubusercontent.com/25714137/60001009-0c799200-9698-11e9-9f9e-14a4089ef2b4.jpg)

**Comment by Nate711** [comment]
Thanks for the reply Kigerzh!
