### ISSUE TITLE
Unknown component in CAD

### ISSUE THREAD

**Issue by kigerzh** [Nate711/StanfordDoggoProject#19]
what is the object under encoder?  Is it  magnet ?     Its path in the CAD  : Full Doggo Assembly v170/single plate design v471:1/AS5048A v26:4/Component2:1

**Comment by HelloPlanet** [comment]
I'm trying to figure this out, too. 
As far as i understand, that would be a magnet needed for use with AS5048A magnetic encoder.

**Comment by Nate711** [comment]
Yup! The magnet comes with the AS5047D encoder (or equivalent encoder), and you superglue it to the rear shaft of the MN5212 motor.
