### ISSUE TITLE
Is there specific wiring schemetics?

### ISSUE THREAD

**Issue by sihanwang-eng** [Nate711/StanfordDoggoProject#20]
Amazing project！

Where can I find the specific wiring schematics diagram? I'm a bit confusing about the wiring things such as how to connect the Teensy Controller with the four Odrives.

**Comment by HelloPlanet** [comment]
You can find wiring information from both source code and picture in readme.md

**_Following are my study, not from Doggo Project Team, use at your own risk!_**

Teensy3.5 --- Logical Function --- Component 
P0 - RX1 - ODrive1
P1 - TX1 - ODrive1

P7 - RX3 - ODrive3?2
P8 - TX3 - ODrive3?2

P9 - RX2 - ODrive2?3
P10 - TX2 - ODrive2?3

P31 - RX4 - ODrive4
P32 - TX4 - ODrive4
