### ISSUE TITLE
How to place IMU board

### ISSUE THREAD

**Issue by kigerzh** [Nate711/StanfordDoggoProject#22]
Hi Nathan,
How to place the IMU board:  the X point to head or Y point to head?

**Comment by HelloPlanet** [comment]
![electronics](https://github.com/Nate711/StanfordDoggoProject/raw/master/images/electronics.jpeg)

as you can see in this picture,
the "front" direction Doggo heading to is X, to his "left" is Y, and the direction to ground is Z.

or maybe i can misunderstood front and back, but i don't think it will matter much, as Doggo is symmetric.

**Comment by CrazyAZ** [comment]
The photo of our electronics plate that @HelloPlanet posted is going to be the best reference as to how we oriented ours.  However, the direction the imu is pointing in the picture is actually with Y pointing forward.  With that said, you can orient it any way you want as long as the pitch is calculated using the right gyro axis in imu.cpp.
