### ISSUE TITLE
Whitch is the xxx.ino project can load to Teensy3.5 Let root work ?

### ISSUE THREAD

**Issue by xuankaicheng** [Nate711/StanfordDoggoProject#26]
Dear :
       I just want konw whitch xxx.ino project can download to Teensy3.5 let root work or just only creat a new project (use the code in src file)?
      
     Thank you!

**Comment by CrazyAZ** [comment]
I'm sorry if I don't fully understand your question.  Our code does not have a .ino file. Instead we use [Platformio](https://platformio.org/) to compile all the code in the src and lib folders and upload it to the teensy.
