### ISSUE TITLE
Question of the hardware list 

### ISSUE THREAD

**Issue by CS4Liu** [Nate711/StanfordDoggoProject#27]
Hello,the project is very great and interesting.And I'm planning to rebuilt following the gudie.You give a hardware list and two version of the Autodesk fusion archive of Doggo.I am some confused about that which version is the hardware list for.Waiting for your answer,Thanks very much!

**Comment by Nate711** [comment]
Hi! The hardware list is for version 2 of the autodesk fusion model.
