### ISSUE TITLE
ICRA Paper

### ISSUE THREAD

**Issue by mmattamala** [Nate711/StanfordDoggoProject#3]
Hi Nathan,

Great work you did here! I was wondering if you're planning to share the ICRA paper (or at least a preprint) soon. I'd love to see it.

Thanks!

**Comment by Nate711** [comment]
Hi, we'll link and publish to arxiv after the conference.

**Comment by mmattamala** [comment]
I saw that Patrick uploaded it today to ArXiv: https://arxiv.org/abs/1905.04254

Thanks!
