### ISSUE TITLE
Error when we download a zip or clone the project, version 2

### ISSUE THREAD

**Issue by mseedman** [Nate711/StanfordDoggoProject#31]
We have been unable to download a zip or clone the project.  Many of the folders are empty.

**Comment by mseedman** [comment]
Error code from fusion: Leg Linkage Assembly.f3d could not be uploaded due to access denied. This occurs when you have lost access to the project of references. Please contact the project moderator for assistance

**Comment by CrazyAZ** [comment]
The folders are empty because you haven't downloaded the submodules. In order to download them you need to run these two commands:
`git submodule init`
`git submodule update`

We are looking into the permissions error with the CAD, but don't know the cause yet.
