### ISSUE TITLE
Motor initial position for robot gait

### ISSUE THREAD

**Issue by nucleusbiao** [Nate711/StanfordDoggoProject#36]
Hi all,

We have prepared everything and assembled the robot. However, currently we have a problem on setting the inital motor position for starting the robot gaits.

Is there anyone knowing how to set up the intial motor position. As far as we know, every time the robot is powered on, the encoder has to calibrate the motor position. It seems that the motor intial position depends on how the legs are manullay placed at the time of powering on. Is that true? Is there a way to sufficiently guarantee that the robot legs can be automatically and correctly configured to a right place no matter how legs are placed when the robot is powered on.

Thanks a lot.

**Comment by CrazyAZ** [comment]
You are correct that the placement of the legs at startup is important.  In order for our code to work all of the upper leg links must be parallel to the ground.  In addition the the linkage attached to motor0 must be the one pointing to the right.

Currently the placement of the legs at startup must be done manually. Hopefully the odrives will get support for absolute encoders soon allowing it to start in any position.
