### ISSUE TITLE
How to calibrate the legs automatically

### ISSUE THREAD

**Issue by Ginot-Joah** [Nate711/StanfordDoggoProject#40]
As using ABI interface on encoders , the leg can only be calibrated to a spectical(actually I put it at) position manually before powering on , or it will keep the position when power is on as its start position and never go to the ideal one . However , the odrive firmware did not have SPI support . 
So how to solve it .....

**Comment by Nate711** [comment]
We use a physical jig to make sure the legs are in alignment before turning the robot on and letting the ODrives do their encoder offset search.
