### ISSUE TITLE
Turning

### ISSUE THREAD

**Issue by methylDragon** [Nate711/StanfordDoggoProject#45]
Repeat of https://github.com/Nate711/Doggo/issues/39

Is the doggo able to rotate on the spot, or take arcing trajectories?

If no, are there any suggestions on how one might help contribute that functionality? My team and I are replicating doggo and if this is a meaningful contribution we can hopefully spare some manpower to try to develop this capability.

**Comment by Nate711** [comment]
Hi methyldragon, thanks for your interest! Right now there's basic support for turning: you can send a 'Y' command to the robot, and then specify a difference in step lengths between the left and right sides by sending 's #', where # represents the step length difference in meters. We usually set the difference to be between -0.08m and 0.08m. 

We also have code to control the robot using a playstation dualshock controller. You can find that code here: https://github.com/stanfordroboticsclub/DoggoCommand
