### ISSUE TITLE
No data sent on Uart1 to Odrive

### ISSUE THREAD

**Issue by caobencheng** [Nate711/StanfordDoggoProject#46]
Hi, Nate711, and the team, I met a problem and do not know why.I have tested the Odrive board with doggo_setup.py, and it looks good. I connected one Odrive board with one motor and the Teensy board through Uart1, then power on. I run the Teensy, and then it started with the led flashing and command line prompts normally. However, the motor has no any movings 
or actions. I send command H, or T, or others, still the motor has no response. I use oscilloscope to check the signals on Pin0(RX1) and Pin1(TX1) of Teensy, the signals keep high without any changing all the time. So I can confirm that there is no UART data sent on Pin1 and no data received on Pin0. What is the reason that no data sent on UART 1 of Teensy? Thanks. BEN

**Comment by caobencheng** [comment]
Hi, Nate711, and the team, I have solved the problem. Right now the TEENSY can successfully control the odrive board and the motor can run according to the E(dancing), T(Trot), R(reset) and S(stop) commands. Thanks. BEN

**Comment by UncleMask** [comment]
I have the same problem, and my LED is not bright, I was wondering how you solve this problem

**Comment by caobencheng** [comment]
Hi, UncleMask, I found the led port type will be changed by IMU function failing,so I  move the calling of "BlinkThread" at last in  chSetup(). You can try.

**Comment by UncleMask** [comment]
Yes, I solved the problem after seeing your another issue. Thanks very much


发件人: caobencheng<mailto:notifications@github.com>
发送时间: 2020年7月24日 0:51
收件人: Nate711/StanfordDoggoProject<mailto:StanfordDoggoProject@noreply.github.com>
抄送: UncleMask<mailto:SIMON.R1995@OUTLOOK.COM>; Comment<mailto:comment@noreply.github.com>
主题: Re: [Nate711/StanfordDoggoProject] No data sent on Uart1 to Odrive (#46)


Hi, UncleMask, I found the led port type will be changed by IMU function failing,so I move the calling of "BlinkThread" at last in chSetup(). You can try.

―

**Comment by niranjan1997** [comment]
> Hi, Nate711, and the team, I have solved the problem. Right now the TEENSY can successfully control the odrive board and the motor can run according to the E(dancing), T(Trot), R(reset) and S(stop) command. Thanks. BEN
Hello @caobencheng, I have the same exact problem, may I know how did you resolve this issue. Thanks in advance.

**Comment by qw7798965** [comment]
Hello @caobencheng, I have the same exact problem, may I know how did you resolve this issue. Thanks in advance.
