### ISSUE TITLE
Where is pcb?

### ISSUE THREAD

**Issue by 790947648** [Nate711/StanfordDoggoProject#6]
Hello, I really like this open source project, I want to know how to find the PCB? I am in China, I think my manufacturing costs are lower.

![11111](https://user-images.githubusercontent.com/51010546/58363207-41e16300-7ed3-11e9-8055-ef06af228f6a.jpg)

**Comment by CrazyAZ** [comment]
Those PCBs were not created by us.  We purchased them from ODrive, so we do not have the design for them. You can find more information about them here: https://odriverobotics.com/

**Comment by 790947648** [comment]
Thank you~
