### ISSUE TITLE
How did you machine the pulley brace?

### ISSUE THREAD

**Issue by mengqlTHU** [Nate711/StanfordDoggoProject#7]
![image](https://user-images.githubusercontent.com/8861816/58462825-3d33dd80-8165-11e9-91c7-3bb4d2fb0b5a.png)
First thank you very much for making the doggo open source.
I am a little confused because this pulley brace seems to have two version: the aluminum one and the ABS plastic one. Which one are you using in the current version? And how did you assemble this part with the bearings? Thanks.

**Comment by ZhangLiangShan** [comment]
According to my understanding, this is just a three-shaft positioning assembly, ensure the parallelism between the three-shaft. I used 6061 aluminum alloy processing, which is not cheap, it cost me 1100 RMB

**Comment by Nate711** [comment]
Hi there, we actually 3d printed that item for the second Doggo we built. It was just cheaper and the aluminum wasn't necessary. The bearings were press-fit in with some super glue.
