### ISSUE TITLE
Where can I find the file of 'tup.config.default'?

### ISSUE THREAD

**Issue by wywhahnj** [Nate711/StanfordDoggoProject#8]

**Comment by Nate711** [comment]
Hi wywhahnj, I added a default tup file that you can edit to match the version of odrive you are using: https://github.com/Nate711/ODrive/blob/master/Firmware/tup.config.default. After your edits you'll need to rename it to tup.config. If you're having trouble, you can reference https://docs.odriverobotics.com/developer-guide

**Comment by wywhahnj** [comment]
Thanks.
